### PR TITLE
bump PolicyAutomation CRD version to v1beta1

### PR DESCRIPTION
**Pull request by ycao56**
Signed-off-by: Yu Cao <ycao@redhat.com>
https://github.com/open-cluster-management/backlog/issues/11395

### CODE REVIEW

**Review by ChunxiAlexLuo — APPROVED** [review]
lgtm

So for creating is still "v1alpha1"

gvrAnsibleJob = schema.GroupVersionResource{Group: "tower.ansible.com", Version: "v1alpha1", Resource: "ansiblejobs"}

**Comment by ChunxiAlexLuo** [comment]
lgtm

**Comment by ycao56** [comment]
@ChunxiAlexLuo correct. but they are supposed to bump to v1beta1 too. So we will need to do another change before the reelase.

**Pull request merged**
