### PR TITLE
QPS tuning

### PR DESCRIPTION
**Pull request by JustinKuli**
This builds off / replaces https://github.com/open-cluster-management/governance-policy-propagator/pull/66.

The controller QPS configuration and use of Patch instead of Update changes are included. The deployment yaml is also updated to expose the metrics endpoint so we can monitor this (and other) metrics more easily in the future.

### CODE REVIEW

**Comment by gparvin** [comment]
Curious if we will need a chart change for the port `8383`

**Review by gparvin — APPROVED** [review]

**Comment by JustinKuli** [comment]
@gparvin Yes, if we wanted to expose the metrics in RHACM.

**Comment by gparvin** [comment]
This fixes issue https://github.com/open-cluster-management/backlog/issues/12828

**Pull request merged**
