### PR TITLE
Upgrade operator sdk

### PR DESCRIPTION
**Pull request by JustinKuli**
This ended up being a hairy upgrade. Not only are a lot of files in new places, but the changes in kubebuilder and the controller-runtime combined with the complicated use of predicates and eventhandlers in our propagation controller made for some odd adjustments.

Movement:
- APIs from `pkg/apis/policy/` to `/api/`
- Controllers from `pkg/controller/*` to `/controllers/*`
- Manager from `cmd/manager/main.go` to `./main.go`
- Deployment YAML from `deploy/` to a Kustomize-based tree in `config/`

I've tried to separate the commits into subjects for easier review, but I'm not sure how successful I was. My initial approach was to follow the [operator-sdk's migration guide](https://sdk.operatorframework.io/docs/building-operators/golang/migration/#configure-your-operator) advice to create a new project and scaffold the APIs there, then migrate the controller code in. But that process is not necessarily reflected in these commits.

If possible, I'd really like to get these commits into the repo as-is (not squashed) since some of the movement and changes would confuse git and cause it to lose the previous history on some of the files - in particular, the propagator controller.

### CODE REVIEW

**Comment by JustinKuli** [comment]
@dhaiducek wanted to check with you - are there other things that rely on having the deploy YAML in `./deploy/` here? If so, can they be updated to this kustomize setup?

Similarly, do we think that there are any external users that we might break by moving our CRDs from `./deploy/crds/` to `./config/crd/bases/`?

Overall I think the movement to a kustomize based approach is good - we don't currently bundle this as an operator for OLM, but this would be a necessary step if we ever did want to.

**Comment by dhaiducek** [comment]
Framework currently uses the deploy directories in the repos, so those commands would need to be updated. I don't think the commands are run during test runs, but I'm also not sure what docs/blogs might point to them. Upstream we uses these commands but they point to the upstream repos, so it should be fine there.

**Comment by JustinKuli** [comment]
/hold

We'll hold on this at least until I have companion PRs for the framework and other repos that might be affected by the deploy directory change.

**Review by mprahl — COMMENTED** [review]
Overall, the PR looks good. The Kustomize commit is hard to digest since it's unclear what is boilerplate from kubebuilder and what is actually needed.

I would suggest breaking out the Kustomize migration to a separate PR so the team can decide on that separately since it is a different approach than the other repos. I'm not saying it's wrong, but it might be something worth discussing as a team first.

**Comment by JustinKuli** [comment]
@mprahl - good idea. I will go back to a deploy/ folder, just need to figure out where exactly to put all the generated files in that.

**Comment by JustinKuli** [comment]
@mprahl rebased and addressed your comments. There is still a little bit of kustomize stuff - but not the full scaffold from the operator-sdk, and the generated files will now be put under the deploy/ folder. Kustomize is no longer required to deploy the propagator, just to generate the saved deployment yaml. Is that a reasonable middle ground?

**Comment by JustinKuli** [comment]
Companion PR: https://github.com/open-cluster-management/governance-policy-framework/pull/169

**Review by mprahl — APPROVED** [review]
Awesome!

**Pull request merged**
